package biblioteca;
// Generated 09-ene-2020 18:15:25 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Autor generated by hbm2java
 */
public class Autor implements java.io.Serializable {

	private int idAutor;
	private String nomAutor;
	private Set<Llibres> llibreses = new HashSet<Llibres>(0);

	public Autor() {
	}

	public Autor(int idAutor) {
		this.idAutor = idAutor;
	}

	public Autor(int idAutor, String nomAutor, Set<Llibres> llibreses) {
		this.idAutor = idAutor;
		this.nomAutor = nomAutor;
		this.llibreses = llibreses;
	}

	public int getIdAutor() {
		return this.idAutor;
	}

	public void setIdAutor(int idAutor) {
		this.idAutor = idAutor;
	}

	public String getNomAutor() {
		return this.nomAutor;
	}

	public void setNomAutor(String nomAutor) {
		this.nomAutor = nomAutor;
	}

	public Set<Llibres> getLlibreses() {
		return this.llibreses;
	}

	public void setLlibreses(Set<Llibres> llibreses) {
		this.llibreses = llibreses;
	}

}
