package biblioteca;
// Generated 09-ene-2020 18:15:25 by Hibernate Tools 4.3.1.Final

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

	private String dni;
	private String nomPersona;
	private Integer telefon;

	public Persona() {
	}

	public Persona(String dni) {
		this.dni = dni;
	}

	public Persona(String dni, String nomPersona, Integer telefon) {
		this.dni = dni;
		this.nomPersona = nomPersona;
		this.telefon = telefon;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNomPersona() {
		return this.nomPersona;
	}

	public void setNomPersona(String nomPersona) {
		this.nomPersona = nomPersona;
	}

	public Integer getTelefon() {
		return this.telefon;
	}

	public void setTelefon(Integer telefon) {
		this.telefon = telefon;
	}

}
